### ISSUE TITLE
PiFaceCam Error on line 9922 - NoneType not iterable

### ISSUE THREAD

**Issue by Morrious** [tensorfactory/PiFaceCam#1]
Can the author of PiFaceCam indicate to me what this error is pertaining to? I followed the full instructions for install with all dependencies and am getting this simple error:

![image](https://user-images.githubusercontent.com/32372811/118911175-a2e17d00-b8da-11eb-8a46-6f14fe7c64fd.png)

**Comment by Morrious** [comment]
Solved! I deleted the data files from the module's library directory, which must have been causing some sort of mismatch. After deleting those, I no longer get the error.

`sudo rm /home/pi/.local/lib/python3.7/site-packages/pifacecam/faceids_image_cache.dat`
`sudo rm /home/pi/.local/lib/python3.7/site-packages/pifacecam/data.dat`
`sudo rm /home/pi/.local/lib/python3.7/site-packages/pifacecam/settings.dat`

**Comment by tensorfactory** [comment]
Glad that you are able to resolve this issue. 
FYI, the error you have encountered was during the reading of the data.dat file.
This file was created from the faceids that were provided. To protect the data, it (so are all ".dat" files) was uniquely encrypted and cannot be read in another RPI.
