### ISSUE TITLE
GPIO  as Optional

### ISSUE THREAD

**Issue by Morrious** [tensorfactory/PiFaceCam#2]
According to the documentation, two GPIO pins (default 19 and 26) need to be used for an indicator LED and exit trigger.  My application utilizes all of the GPIO pins, so I run into issues when PiFaceCam utilizes 2 pins that I need for other uses. Providing an alternate way to exit the system would be ideal, but at least being able to pass a value of -1 or something to disable the GPIO functionality would be helpful.

**Comment by tensorfactory** [comment]
Hi Morrious,
	Thank you for your valuable suggestion. We think that creating an option to disable one or both the LED/Shutdown GPIOs is feasible. However, our resources are currently tied up with another project that we are not able to work on it immediately. Please allow 2 to 3 weeks for us to get this done.

Thanks

KC Yee

**Comment by Morrious** [comment]
Closed via pre-release mentioned in [other issue here](https://github.com/tensorfactory/PiFaceCam/issues/3#issue-913785023).
