### ISSUE TITLE
Rotate Camera Input Image

### ISSUE THREAD

**Issue by Morrious** [tensorfactory/PiFaceCam#5]
PiFaceCam is currently limited to the camera being mounted upright. If the camera is mounted upside down, facial recognition fails, the image is streamed to the browser upside down, etc. Is it possible to add a 90, 180, 270 degree offset option? Right now I am in need of mounting my camera upside down, but this is not an option with facial recognition.

Thank you,
Morrious

**Comment by tensorfactory** [comment]
Hi Morrious,
    Thank you for your valuable feedback. Let us do some assessment and come back to you in a few days.

Rgds
KC Yee

**Comment by tensorfactory** [comment]
Hi Morrious,
    We have uploaded pifacecam-1.2.1a1-cp37-abi3-linux_armv7l.whl to the pre-release folder. With this version, you can set the camera rotation to 0 or 180. We were not able to include 90 or 270 degrees as the neural network we used to analyze images has a fixed input dimension. The 2 new parameters added to this version are "usb_cam_rotation" and "picam_cam_rotation". They can accept an integer or float value of either 0 or 180. 
  Please let us know if you encounter any issues.

Thanks

Rgds
KC Yee

**Comment by Morrious** [comment]
@tensorfactory
Great! Thank you so much, I will try it out and let you know if I have any issues.

**Comment by Morrious** [comment]
It's been working great so far, thank you!

Did you make an update to the output for "face_confidence_percentage_list" as well? There used to be a bug where it output the face ID instead of the percentage. My logs show that since I installed this latest pre-release, that bug is gone.
![image](https://user-images.githubusercontent.com/32372811/124216072-372e2a80-daaa-11eb-8f30-347b19a4ec03.png)

**Comment by tensorfactory** [comment]
Hi Morrious,
   Thank you very much for your feedback. Yes, we have fixed the bug. Also, we have released this 1.2.1a1 at pypi.org under version 1.2.2.
Rgds
KC Yee

**Comment by Morrious** [comment]
Thank you!
